### ISSUE TITLE
connection refused in /foxess-mqtt/src/model/mhredis.php:25

### ISSUE THREAD

**Issue by azizth** [mhzawadi/foxess-mqtt#45]
Hello , 

I have probleme with connection refused in /foxess-mqtt/src/model/mhredis.php:25 I cannot find why

```
2024-03-29T19:45:43.046149761Z This is our timezone: Africa/Tunis
2024-03-29T19:45:43.055466012Z PHP Fatal error:  Uncaught RedisException: Connection refused in /foxess-mqtt/src/model/mhredis.php:25
2024-03-29T19:45:43.055758899Z Stack trace:
2024-03-29T19:45:43.055790148Z #0 /foxess-mqtt/src/model/mhredis.php(25): Redis->connect()
2024-03-29T19:45:43.055821585Z #1 /foxess-mqtt/src/model/data.php(20): MHorwood\foxess_mqtt\model\mhredis->__construct()
2024-03-29T19:45:43.055877369Z #2 /foxess-mqtt/src/controller/foxess_data.php(31): MHorwood\foxess_mqtt\model\data->__construct()
2024-03-29T19:45:43.055934292Z #3 /foxess-mqtt/run.php(8): MHorwood\foxess_mqtt\controller\foxess_data->__construct()
2024-03-29T19:45:43.055963128Z #4 {main}
2024-03-29T19:45:43.056020177Z   thrown in /foxess-mqtt/src/model/mhredis.php on line 25
```
My Config File : 
{
  "foxess_apikey": "my API",
  "foxess_lang": "en",
  "mqtt_host": "localhost",
  "mqtt_port": "1883",
  "mqtt_user": "my username",
  "mqtt_pass": "My Key",
  "mqtt_topic": "foxesscloud",
  "log_level": 2,
  "total_over_time": true,
  "redis_server": "localhost",
  "redis_port": "6379"
}

Redis server is working and port 6379 is open ( tested with telnet)

**Comment by mhzawadi** [comment]
Hi @azizth,

From your config, that redis IP wont work. localhost will be the foxess-mqtt container, not the docker host.

Are you running redis as a container as well or as a service on the docker host?

If its a container, the container name will be the `redis_server` setting
If its a service on the docker host, you will need the IP of the docker host as the `redis_server` setting

**Comment by azizth** [comment]
Hi ,
Thank you for your support. 👍 
The Foxess-MQTT Docker now communicates with the Redis server. Redis is installed as a service on a Debian machine, which hosts the Foxess-MQTT Docker. Therefore, you must use the IP address of the Debian machine, not localhost. Here is the configuration:
```
{
  "foxess_apikey": "XXXXXXXXXXXXX",
  "foxess_lang": "en",
  "mqtt_host": "192.168.1.3",
  "mqtt_port": "1883",
  "mqtt_user": "XXXXXX",
  "mqtt_pass": "XXXXXX",
  "mqtt_topic": "foxesscloud",
  "log_level": 1,
  "total_over_time": true,
  "redis_server": "192.168.1.3",
  "redis_port": "6379"
}
```
In the Redis server's config file (/etc/redis/redis.conf), you need to comment out the line "bind 127.0.0.1" and disable protected mode: "protected-mode no".

here the foxesslog : 

`2024-03-30T16:37:51.878572435Z This is our timezone: Africa/Tunis
2024-03-30T16:37:51.882005489Z 2024-03-30 17:37:51 [INFO] Using MQTT topic: foxesscloud
2024-03-30T16:37:51.882152818Z 2024-03-30 17:37:51 [INFO] total over time is: true
2024-03-30T16:37:51.893862338Z 2024-03-30 17:37:51 [INFO] Collect data from the cloud
2024-03-30T16:37:52.423403709Z 2024-03-30 17:37:52 [INFO] Data collected
2024-03-30T16:37:52.423558469Z 2024-03-30 17:37:52 [INFO] Start of processing the data
2024-03-30T16:37:52.423589821Z 2024-03-30 17:37:52 [INFO] todayYield
2024-03-30T16:37:52.451129759Z 2024-03-30 17:37:52 [INFO] Post 18.3kw of todayYield to MQTT
2024-03-30T16:37:52.452583486Z 2024-03-30 17:37:52 [INFO] pvPower
2024-03-30T16:37:52.455165367Z 2024-03-30 17:37:52 [INFO] Post 0.142kw of pvPower to MQTT
2024-03-30T16:37:52.456960620Z 2024-03-30 17:37:52 [INFO] pv1Volt
2024-03-30T16:37:52.460659797Z 2024-03-30 17:37:52 [INFO] Post 237.3 of pv1Volt to MQTT
2024-03-30T16:37:52.460803993Z 2024-03-30 17:37:52 [INFO] pv1Current
2024-03-30T16:37:52.463712277Z 2024-03-30 17:37:52 [INFO] Post 0.6 of pv1Current to MQTT
2024-03-30T16:37:52.463793153Z 2024-03-30 17:37:52 [INFO] pv1Power
2024-03-30T16:37:52.467087582Z 2024-03-30 17:37:52 [INFO] Post 0.142kw of pv1Power to MQTT
2024-03-30T16:37:52.467241870Z 2024-03-30 17:37:52 [INFO] pv2Volt
2024-03-30T16:37:52.470678403Z 2024-03-30 17:37:52 [INFO] Post 0 of pv2Volt to MQTT
2024-03-30T16:37:52.470870236Z 2024-03-30 17:37:52 [INFO] pv2Current
2024-03-30T16:37:52.474180669Z 2024-03-30 17:37:52 [INFO] Post 0 of pv2Current to MQTT
2024-03-30T16:37:52.474256404Z 2024-03-30 17:37:52 [INFO] pv2Power
2024-03-30T16:37:52.476657105Z 2024-03-30 17:37:52 [INFO] Post 0kw of pv2Power to MQTT
2024-03-30T16:37:52.477581783Z 2024-03-30 17:37:52 [INFO] pv3Volt
2024-03-30T16:37:52.480802739Z 2024-03-30 17:37:52 [INFO] Post 0 of pv3Volt to MQTT
2024-03-30T16:37:52.480933692Z 2024-03-30 17:37:52 [INFO] pv3Current
2024-03-30T16:37:52.487044977Z 2024-03-30 17:37:52 [INFO] Post 0 of pv3Current to MQTT
2024-03-30T16:37:52.487480193Z 2024-03-30 17:37:52 [INFO] pv3Power
2024-03-30T16:37:52.489897598Z 2024-03-30 17:37:52 [INFO] Post 0kw of pv3Power to MQTT
2024-03-30T16:37:52.491375624Z 2024-03-30 17:37:52 [INFO] pv4Volt
2024-03-30T16:37:52.495034634Z 2024-03-30 17:37:52 [INFO] Post 0 of pv4Volt to MQTT
2024-03-30T16:37:52.495339347Z 2024-03-30 17:37:52 [INFO] pv4Current
2024-03-30T16:37:52.498092399Z 2024-03-30 17:37:52 [INFO] Post 0 of pv4Current to MQTT
2024-03-30T16:37:52.498166047Z 2024-03-30 17:37:52 [INFO] pv4Power
2024-03-30T16:37:52.500330179Z 2024-03-30 17:37:52 [INFO] Post 0kw of pv4Power to MQTT
2024-03-30T16:37:52.503223432Z 2024-03-30 17:37:52 [INFO] epsCurrentR
2024-03-30T16:37:52.505499564Z 2024-03-30 17:37:52 [INFO] Post 0 of epsCurrentR to MQTT
2024-03-30T16:37:52.505746179Z 2024-03-30 17:37:52 [INFO] epsVoltR
2024-03-30T16:37:52.511356678Z 2024-03-30 17:37:52 [INFO] Post 0 of epsVoltR to MQTT
2024-03-30T16:37:52.511439969Z 2024-03-30 17:37:52 [INFO] epsPowerR
2024-03-30T16:37:52.511468475Z 2024-03-30 17:37:52 [INFO] Post 0kw of epsPowerR to MQTT
2024-03-30T16:37:52.511563137Z 2024-03-30 17:37:52 [INFO] RCurrent
2024-03-30T16:37:52.518406932Z 2024-03-30 17:37:52 [INFO] Post 0.7 of RCurrent to MQTT
2024-03-30T16:37:52.518521930Z 2024-03-30 17:37:52 [INFO] RVolt
2024-03-30T16:37:52.522204726Z 2024-03-30 17:37:52 [INFO] Post 234.3 of RVolt to MQTT
2024-03-30T16:37:52.522385215Z 2024-03-30 17:37:52 [INFO] RFreq
2024-03-30T16:37:52.524777693Z 2024-03-30 17:37:52 [INFO] Post 50.05kw of RFreq to MQTT
2024-03-30T16:37:52.525703429Z 2024-03-30 17:37:52 [INFO] RPower
2024-03-30T16:37:52.528281045Z 2024-03-30 17:37:52 [INFO] Post 0.125kw of RPower to MQTT
2024-03-30T16:37:52.529555057Z 2024-03-30 17:37:52 [INFO] SCurrent
2024-03-30T16:37:52.532942948Z 2024-03-30 17:37:52 [INFO] Post 0 of SCurrent to MQTT
2024-03-30T16:37:52.533082691Z 2024-03-30 17:37:52 [INFO] SVolt
2024-03-30T16:37:52.541057127Z 2024-03-30 17:37:52 [INFO] Post 0 of SVolt to MQTT
2024-03-30T16:37:52.541136955Z 2024-03-30 17:37:52 [INFO] SFreq
2024-03-30T16:37:52.541193143Z 2024-03-30 17:37:52 [INFO] Post 0kw of SFreq to MQTT
2024-03-30T16:37:52.543586199Z 2024-03-30 17:37:52 [INFO] SPower
2024-03-30T16:37:52.547165601Z 2024-03-30 17:37:52 [INFO] Post 0kw of SPower to MQTT
2024-03-30T16:37:52.548095660Z 2024-03-30 17:37:52 [INFO] TCurrent
2024-03-30T16:37:52.551481101Z 2024-03-30 17:37:52 [INFO] Post 0 of TCurrent to MQTT
2024-03-30T16:37:52.551587783Z 2024-03-30 17:37:52 [INFO] TVolt
2024-03-30T16:37:52.556481798Z 2024-03-30 17:37:52 [INFO] Post 0 of TVolt to MQTT
2024-03-30T16:37:52.556630891Z 2024-03-30 17:37:52 [INFO] TFreq
2024-03-30T16:37:52.559422733Z 2024-03-30 17:37:52 [INFO] Post 0kw of TFreq to MQTT
2024-03-30T16:37:52.560267217Z 2024-03-30 17:37:52 [INFO] TPower
2024-03-30T16:37:52.563244204Z 2024-03-30 17:37:52 [INFO] Post 0kw of TPower to MQTT
2024-03-30T16:37:52.564187978Z 2024-03-30 17:37:52 [INFO] ambientTemperation
2024-03-30T16:37:52.568146999Z 2024-03-30 17:37:52 [INFO] Post 47 of ambientTemperation to MQTT
2024-03-30T16:37:52.568293830Z 2024-03-30 17:37:52 [INFO] boostTemperation
2024-03-30T16:37:52.571731404Z 2024-03-30 17:37:52 [INFO] Post 35 of boostTemperation to MQTT
2024-03-30T16:37:52.572335727Z 2024-03-30 17:37:52 [INFO] invTemperation
2024-03-30T16:37:52.574477804Z 2024-03-30 17:37:52 [INFO] Post 35 of invTemperation to MQTT
2024-03-30T16:37:52.574739762Z 2024-03-30 17:37:52 [INFO] loadsPower
2024-03-30T16:37:52.577889645Z 2024-03-30 17:37:52 [INFO] Post 0kw of loadsPower to MQTT
2024-03-30T16:37:52.579591238Z 2024-03-30 17:37:52 [INFO] generationPower
2024-03-30T16:37:52.580659499Z 2024-03-30 17:37:52 [INFO] Post 0.125kw of generationPower to MQTT
2024-03-30T16:37:52.581989787Z 2024-03-30 17:37:52 [INFO] feedinPower
2024-03-30T16:37:52.584907601Z 2024-03-30 17:37:52 [INFO] Post 0.125KWh of feedinPower to MQTT
2024-03-30T16:37:52.588844516Z 2024-03-30 17:37:52 [INFO] Post 0.125kw of feedinPower to MQTT
2024-03-30T16:37:52.589589673Z 2024-03-30 17:37:52 [INFO] gridConsumptionPower
2024-03-30T16:37:52.592048988Z 2024-03-30 17:37:52 [INFO] Post 0KWh of gridConsumptionPower to MQTT
2024-03-30T16:37:52.595059434Z 2024-03-30 17:37:52 [INFO] Post 0kw of gridConsumptionPower to MQTT
2024-03-30T16:37:52.595907281Z 2024-03-30 17:37:52 [INFO] generation
2024-03-30T16:37:52.598439362Z 2024-03-30 17:37:52 [INFO] Post 44.9kw of generation to MQTT
2024-03-30T16:37:52.599387745Z 2024-03-30 17:37:52 [INFO] runningState
2024-03-30T16:37:52.603250113Z 2024-03-30 17:37:52 [INFO] Post illegal of runningState to MQTT
2024-03-30T16:37:52.603433679Z 2024-03-30 17:37:52 [INFO] Data procssed and posted to MQTT
2024-03-30T16:37:52.603491028Z 2024-03-30 17:37:52 [INFO] Work complete`
